### ISSUE TITLE
Is it suitable for the following idea?

### ISSUE THREAD

**Issue by RoseRiyadh** [fresns/plugin-manager#2]
good day, i want to check if the package is suitable to my project idea which is : a multi-tenancy system, that i want to build plugins for and whenever an admin in a tenant activates a plugin they simply can and be added to their tenant. is this possible with this package?

**Comment by mouyong** [comment]
Yes, it's achievable.

Scenario one: In Laravel, by installing the plugin LaravelSaas, you can transition your laravel project into a SaaS project. Activate the plugin in the central application and in the tenant applications, allowing for user choice in determining the availability of plugin functionalities.

Scenario two: Each tenant possesses entirely independent plugins and chooses to install their own. This necessitates some technical adjustments to dynamically configure the plugins activated by the tenant, achievable through `config(['plugins.manager.default.file' => base_path("fresns-{$tenantId}.json")])`.

Should you require our technical support, feel free to reach out via the link below:
https://fresns.org/community/teams.html.

Email: my24251325@gmail.com

Reference link:
- LaravelSaaS: https://marketplace.plugins-world.cn/market-place/plugins/detail/LaravelSaas
- DcatSaas: https://learnku.com/articles/83896
